[profile.default]
src = "contracts"
out = "foundry-out"
libs = ["lib", "node_modules"]
solc_version = "0.8.28"
auto_detect_remappings = true
bytecode_hash = "none"
cbor_metadata = false
gas_limit = "3000000000"
extra_output = ["metadata", "storageLayout"]
verbosity = 2
ignored_error_codes = []


fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" }, 
    { access = "read", path = "foundry-out/" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" }
]




remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@selfxyz/contracts/=node_modules/@selfxyz/contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@self/=node_modules/@selfxyz/contracts/contracts/",
    "@Cyfrin/foundry-devops/=lib/foundry-devops/src/",
]

[rpc_endpoints]

celo = "https://celo-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
celo_sepolia="https://celo-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
celo_alfajores="https://celo-alfajores.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
celo_sepolia = { key = "${CELO_SEPOLIA_EXPLORER_API_KEY}", url = "https://celo-sepolia.blockscout.com/api" }
celo_alfajores = { key = "${CELO_ALFAJORES_EXPLORER_API_KEY}", url = "https://alfajores.celoscan.io/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
