[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

[profile.test]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

[profile.deploy]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

# Test configuration
[profile.test]
fuzz = { runs = 1000 }
invariant = { runs = 256, depth = 15, fail_on_revert = false }

# Fork testing
[profile.fork]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2

# Gas reporting
[profile.gas]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false
verbosity = 2
gas_reports = ["*"]





