[profile.default]
src = "contracts"
out = "foundry-out"
libs = ["lib", "node_modules"]
solc_version="0.8.28"

remappings = [
    "@balancer-labs/v3-interfaces/=lib/balancer-v3-monorepo/pkg/interfaces/",
    "@uniswap/lending-hook/=lib/hookathon-unilend/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "@selfxyz/contracts/=node_modules/@selfxyz/contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-periphery/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
